Repository boostcamp-2020/Project01-B-User-Event-Collector, pull requests merged in 2020-12, with the labels that each got.

#164 [iOS] 재생화면 곡 정보 표시 뷰 구현 #109, #112, #114
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Player.swift
  MiniVibe/MiniVibe/Views/PlayerControls.swift
  MiniVibe/MiniVibe/Views/PlayerHeader.swift
  MiniVibe/MiniVibe/Views/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/RepeatButton.swift
Labels: enhancement, iOS🍎

#160 장르카드, 매거진, 스테이션 리스트 구현
  client/components/molecules/GenreCard/GenreCard.stories.tsx
  client/components/molecules/GenreCard/GenreCard.tsx
  client/components/organisms/CardLists/GenreCardList/GenreCardList.stories.tsx
  client/components/organisms/CardLists/GenreCardList/GenreCardList.tsx
  client/components/organisms/CardLists/MagazineList/MagazineList.stories.tsx
  client/components/organisms/CardLists/MagazineList/MagazineList.tsx
  client/components/organisms/CardLists/StationCardList/StationCard.stories.tsx
  client/components/organisms/CardLists/StationCardList/StationCardList.tsx
  client/components/organisms/Cards/MagazineCard/MagazineCard.tsx
  client/components/organisms/Cards/StationCard/StationCard.tsx
  client/interfaces/props.ts
Labels: FE, Web

#168 [iOS] 이어지는 노래 리스트 뷰 및 다중 선택 구현 #121, #126
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/MultiselectTabBar.swift
  MiniVibe/MiniVibe/Views/MultiselectTabBarItems.swift
  MiniVibe/MiniVibe/Views/MultiselectTrackRow.swift
  MiniVibe/MiniVibe/Views/UpNextList.swift
Labels: enhancement, iOS🍎

#178 [iOS] 재생화면 구성 #177
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Common/MainTab.swift
  MiniVibe/MiniVibe/Views/Common/MultiselectTabBar.swift
  MiniVibe/MiniVibe/Views/Common/MultiselectTabBarItems.swift
  MiniVibe/MiniVibe/Views/Player/MultiselectTrackRow.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/PlayerHeader.swift
  MiniVibe/MiniVibe/Views/Player/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/Player/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Player/RepeatButton.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
Labels: PairProgramming, enhancement, iOS🍎

#179 카드 스크롤 리스트 리팩토링
  client/components/organisms/CardLists/GenreCardList/GenreCardList.tsx
  client/components/organisms/CardLists/MagazineList/MagazineList.styles.tsx
  client/components/organisms/CardScrollList/CardScrollList.styles.tsx
Labels: FE, Web

#180 [iOS] 플레이어 메뉴 화면 구현 #119
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/MenuButton.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/PlayerMenu.swift
Labels: enhancement, iOS🍎

#182 [iOS] 가사 보기 뷰 구현 #116
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/Player/PlayerSliderView.swift
  MiniVibe/MiniVibe/Views/Player/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
Labels: enhancement, iOS🍎

#185 [iOS] 비슷한 아티스트 목록, 아티스트 썸네일 구현 #128 #131
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/artist.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/artist.imageset/artist.png
  MiniVibe/MiniVibe/Views/ArtistItem.swift
  MiniVibe/MiniVibe/Views/ArtistSection.swift
  MiniVibe/MiniVibe/Views/ArtistThumbnail.swift
Labels: enhancement, iOS🍎

#186 [iOS] 아티스트 메뉴 뷰 구현 #132
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/ArtistMenu.swift
Labels: enhancement, iOS🍎

#183 [FE] 보관함에 필요한 카드 리스트 구현 / 아티스트 썸네일에 href 추가 / props 리팩토링
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.stories.tsx
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.stories.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.stories.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.styles.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.tsx
  client/components/organisms/Library/LibraryHeader/LibraryHeader.stories.tsx
  client/components/organisms/Library/LibraryHeader/LibraryHeader.tsx
  client/interfaces/props.ts
Labels: FE, Web

#187 [FE] alias path 리팩토링 & 오타 수정
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.stories.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: FE, Web

#188 [iOS] 아티스트 앨범 화면 구현 #136
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/ArtistAlbumGridView.swift
  MiniVibe/MiniVibe/Views/Common/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGridView.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#189 [iOS] 앨범 화면 구성 #139 #141
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/artist.imageset/Contents.json
  MiniVibe/MiniVibe/Views/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/PlaylistAlbumInfo.swift
Labels: enhancement, iOS🍎

#190 [iOS] 아티스트 화면 구성 #131
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/ArtistSection.swift
  MiniVibe/MiniVibe/Views/ArtistView.swift
Labels: enhancement, iOS🍎

#192 [FE] player controller button group 컴포넌트 구현
  client/assets/global.css
  client/components/molecules/PlayControllerButtons/PlayControllerButtons.stories.tsx
  client/components/molecules/PlayControllerButtons/PlayControllerButtons.tsx
  client/components/molecules/PlayControllerButtons/index.ts
Labels: FE, Web, enhancement

#196 [FE] 보관함 템플릿 구현 & 헤더사이드메뉴 로그인 상태로 변경 & 헤더사이드메뉴 커서 변경
  client/components/atoms/MenuLink/MenuLink.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.styles.tsx
  client/pages/_app.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
Labels: FE, Web

#199 [FE] 차트 리스트 컴포넌트
  client/components/molecules/ChartCard/ChartCard.styles.tsx
  client/components/molecules/ChartCard/ChartCard.tsx
  client/components/organisms/CardLists/ChartCardList/ChartCardList.stories.tsx
  client/components/organisms/CardLists/ChartCardList/ChartCardList.tsx
  client/interfaces/props.ts
Labels: FE, Web

#198 [FE] 트랙 로우 카드 컴포넌트
  client/components/atoms/CheckBox/CheckBox.stories.tsx
  client/components/atoms/CheckBox/CheckBox.tsx
  client/components/atoms/Text/HiddenText.tsx
  client/components/molecules/ChartCard/ChartCard.stories.tsx
  client/components/molecules/ChartCard/ChartCard.styles.tsx
  client/components/molecules/ChartCard/ChartCard.tsx
  client/components/molecules/TrackPlayButton/TrackPlayButton.stories.tsx
  client/components/molecules/TrackPlayButton/TrackPlayButton.styles.tsx
  client/components/molecules/TrackPlayButton/TrackPlayButton.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.stories.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.styles.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.tsx
Labels: FE, Web

#205 [FE] DJ 스테이션 템플릿 구현 & width/padding 조절
  client/components/atoms/Text/Text.stories.tsx
  client/components/atoms/Text/Text.styles.tsx
  client/components/atoms/Text/Text.tsx
  client/components/organisms/CardListContainer/CardListContainer.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.tsx
  client/pages/dj-station.tsx
  client/pages/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
Labels: FE, Web

#206 [FE] progress bar 구현
  client/assets/global.css
  client/components/molecules/DropdownMenu/DropdownMenu.stories.tsx
  client/components/molecules/DropdownMenu/DropdownMenu.tsx
  client/components/molecules/DropdownMenu/index.ts
  client/components/molecules/DropdownMenu/index.tsx
  client/components/molecules/MainMenu/MainMenu.stories.tsx
  client/components/molecules/MainMenu/MainMenu.tsx
  client/components/molecules/MainMenu/index.ts
  client/components/molecules/MainMenu/index.tsx
  client/components/molecules/PlayControllerButtons/PlayControllerButtons.stories.tsx
  client/components/molecules/PlayControllerButtons/index.ts
  client/components/molecules/PlayControllerButtons/index.tsx
  client/components/molecules/ProgressBar/ProgressBar.stories.tsx
  client/components/molecules/ProgressBar/index.tsx
  client/components/molecules/SlideNextButton/SlideNextButton.stories.tsx
  client/components/molecules/SlideNextButton/SlideNextButton.styles.tsx
  client/components/molecules/SlideNextButton/index.ts
  client/components/molecules/SlideNextButton/index.tsx
  client/components/molecules/SlidePrevButton/SlidePrevButton.stories.tsx
  client/components/molecules/SlidePrevButton/SlidePrevButton.styles.tsx
  client/components/molecules/SlidePrevButton/index.ts
  client/components/molecules/SlidePrevButton/index.tsx
  client/components/molecules/SubMenu/SubMenu.stories.tsx
  client/components/molecules/SubMenu/SubMenu.tsx
  client/components/molecules/SubMenu/index.ts
  client/components/molecules/SubMenu/index.tsx
Labels: FE, Web

#209 [iOS] 앨범 화면, 아티스트 화면 UI 연결 #201
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Views/Album/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistAlbumGridView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistItem.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistThumbnail.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSection.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlayAndShuffle.swift
  MiniVibe/MiniVibe/Views/Common/Components/SectionTitle.swift
  MiniVibe/MiniVibe/Views/Common/Components/ThumbnailItem.swift
  MiniVibe/MiniVibe/Views/Common/Menu/ArtistMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuButton.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailSection.swift
  MiniVibe/MiniVibe/Views/Common/TrackRow.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerHeader.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerSliderView.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Components/RepeatButton.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Profile/ProfileView.swift
  MiniVibe/MiniVibe/Views/Today/Components/MagazineItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/PreviewItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/RecommandedPlayListItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/StationItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineSection.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
Labels: PairProgramming, enhancement, iOS🍎

#218 [FE] Button(Add & Heart) / Detail Page Header, Template / Button Group 구현 & 사소한 CSS 수정
  client/components/atoms/Button/AddButton.tsx
  client/components/atoms/Heart/Heart.tsx
  client/components/atoms/MenuLink/MenuLink.tsx
  client/components/organisms/CardLists/ContentsCardList/ContentsCardList.tsx
  client/components/organisms/ContentsButtonGroup/ContentsButtonGroup.stories.tsx
  client/components/organisms/ContentsButtonGroup/index.tsx
  client/components/organisms/DetailHeader/DetailHeader.stories.tsx
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/HeaderButtonGroup/HeaderButtonGroup.stories.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/pages/album/sample.tsx
  client/pages/artist/sample.tsx
  client/pages/dj-station.tsx
  client/pages/library/tracks.tsx
  client/pages/mixtape/sample.tsx
  client/pages/playlist/sample.tsx
Labels: FE, Web

#211 [iOS] Track Row의 종류에 따른 구현 #210
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Extension/Image+TrackRowConfigure.swift
  MiniVibe/MiniVibe/Views/Album/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSection.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/TrackRow.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Player/MultiselectTrackRow.swift
Labels: enhancement, iOS🍎

#221 [FE] Play Controller 컴포넌트 스켈레톤 구현
  client/components/molecules/PlayControllerButtons/PlayControllerButtons.stories.tsx
  client/components/molecules/PlayControllerButtons/index.tsx
  client/components/molecules/ProgressBar/index.tsx
  client/components/organisms/PlayController/PlayController.stories.tsx
  client/components/organisms/PlayController/index.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
Labels: FE, Web

#222 [FE] TrackInfo, TrackCard, PlayerTrackCard 컴포넌트
  client/components/atoms/A/A.styles.tsx
  client/components/molecules/ChartCard/ChartCard.tsx
  client/components/molecules/TrackCard/TrackCard.stories.tsx
  client/components/molecules/TrackCard/index.tsx
  client/components/molecules/TrackInfo/TrackInfo.stories.tsx
  client/components/molecules/TrackInfo/index.tsx
  client/components/molecules/TrackPlayButton/TrackPlayButton.stories.tsx
  client/components/molecules/TrackPlayButton/index.tsx
  client/components/organisms/CardLists/ChartCardList/ChartCardList.stories.tsx
  client/components/organisms/CardLists/TrackRowList/TrackRowList.stories.tsx
  client/components/organisms/Cards/PlayerTrackCard/PlayerTrackCard.stories.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/interfaces/props.ts
Labels: FE, Web

#226 [iOS] 차트 뷰 구성 #130
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Chart.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#232 [FE] VIBE MAG 템플릿 구현 & CSS 변경
  client/components/atoms/A/A.styles.tsx
  client/components/atoms/Label/Label.styles.tsx
  client/pages/dj-station.tsx
  client/pages/index.tsx
  client/pages/magazines.tsx
Labels: FE, Web

#230 [iOS] 메뉴 화면에서 버튼을 눌러 화면전환 할 때 같은화면으로 두번이상 전환할 수 없는 문제 #224
  MiniVibe/MiniVibe/Models/NowPlaying.swift
Labels: bug, iOS🍎

#231 [iOS] 비슷한 아티스트를 눌러도 아티스트 화면으로 이동하지 않는 문제 #223
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistItem.swift
Labels: bug, iOS🍎

#233 [iOS] 앨범화면 썸네일 크기가 작게 출력되는 문제 #225
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
Labels: bug, iOS🍎

#239 [iOS] Track Row에서 발생할 수 있는 interaction이 빠진 문제 #228
  MiniVibe/MiniVibe/Views/Album/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
Labels: bug, iOS🍎

#240 [iOS] 앨범 표시 화면 UI 수정 #227
  MiniVibe/MiniVibe/Views/Album/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
Labels: bug, iOS🍎

#241 [iOS] PlayerPreview로 인해 화면 하단이 가려지는 문제 #229
  MiniVibe/MiniVibe/Views/Album/AlbumPlaylistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Today/StationList.swift
Labels: bug, iOS🍎

#242 [FE] 트랙 상세 페이지에 필요한 컴포넌트 및 트랙 상세 페이지 템플릿 구현
  client/components/organisms/DetailHeader/DetailHeader.stories.tsx
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/HeaderButtonGroup/HeaderButtonGroup.stories.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/pages/track/sample.tsx
Labels: FE, Web

#244 [FE] Playtime, VolumnController, PlaylistDisplayButton 컴포넌트 구현 및 PlayController 컴포넌트에 추가
  client/components/atoms/Playtime/Playtime.stories.tsx
  client/components/atoms/Playtime/index.tsx
  client/components/molecules/PlaylistDisplayButton/PlaylistButton.stories.tsx
  client/components/molecules/PlaylistDisplayButton/index.tsx
  client/components/molecules/ProgressBar/index.tsx
  client/components/molecules/VolumnController/VolumnController.stories.tsx
  client/components/molecules/VolumnController/index.tsx
  client/components/organisms/PlayController/index.tsx
  client/utils/sample.ts
  client/utils/time.ts
Labels: FE, Web

#246 [iOS] 보관함 뼈대 및 좋아하는 노래, 앨범 뷰 구성 #111, #115, #118
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/Views/Library/LibraryAlbumsView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
Labels: enhancement, iOS🍎

#248 [FE] 매거진 상세 페이지 템플릿 구현 & 이달의 노래에 있는 트랙 클릭 시 트랙 상세 페이지로 연결 & 검색창 크기 조절
  client/components/atoms/Input/Input.styles.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/interfaces/props.ts
  client/pages/magazines/sample.tsx
  client/pages/this-month.tsx
Labels: FE, Web

#252 [iOS] 보관함 화면 구현
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Library/LibraryAlbumsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryArtistRow.swift
  MiniVibe/MiniVibe/Views/Library/LibraryArtistsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryPlayListRow.swift
  MiniVibe/MiniVibe/Views/Library/LibraryPlayListView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
Labels: enhancement, iOS🍎

#253 [iOS] 검색화면의 Search bar 구현 및 키보드 대응 #122, #191
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Extension/View+dismissKeyboard.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Search.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlayAndShuffle.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Genre/SearchBar.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerSlider.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#250 [FE] 트랙 로우 카드 좋아요 버튼 수정 & 헤더사이드바 CSS 수정
  client/components/atoms/Input/Input.styles.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.styles.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.styles.tsx
Labels: FE, Web

#255 Article 화면 구현 #135
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Profile/Article.swift
Labels: enhancement, iOS🍎

#258 [iOS] 검색화면의 뉴스, 장르 구성 #122, #254, #120
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Search.swift
  MiniVibe/MiniVibe/Views/Genre/GenreSection.swift
  MiniVibe/MiniVibe/Views/Genre/NewsSection.swift
  MiniVibe/MiniVibe/Views/Genre/SearchBar.swift
Labels: enhancement, iOS🍎

#264 [FE] Chart 템플릿 구현
  client/components/organisms/CardLists/ChartCardList/ChartCardList.stories.tsx
  client/components/organisms/CardLists/ChartCardList/index.tsx
  client/components/organisms/CardLists/GenreCardList/GenreCardList.stories.tsx
  client/components/organisms/CardLists/GenreCardList/index.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.stories.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.styles.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.tsx
  client/components/organisms/HeaderSideBar/index.ts
  client/components/organisms/HeaderSideBar/index.tsx
  client/pages/chart.tsx
  client/pages/dj-station.tsx
Labels: FE, Web

#262 [FE] checkbox 컴포넌트
  client/components/atoms/CheckBox/CheckBox.stories.tsx
  client/components/atoms/CheckBox/CheckBox.tsx
  client/components/atoms/CheckBox/index.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
Labels: FE, Web

#260 [FE] 플레이어트랙리스트 , 플레이리스트카드리스트 컴포넌트
  client/components/molecules/TrackCard/index.tsx
  client/components/molecules/TrackInfo/index.tsx
  client/components/organisms/CardLists/PlayerTrackList/PlayerTrackList.stories.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/CardLists/PlaylistCardList/PlaylistCardList.stories.tsx
  client/components/organisms/CardLists/PlaylistCardList/index.tsx
  client/components/organisms/Cards/PlayTrackCard/PlayTrackCard.stories.tsx
  client/components/organisms/Cards/PlayTrackCard/index.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/interfaces/props.ts
Labels: FE, Web

#266 [iOS] 검색 화면, 보관함 화면에서 재생화면을 통한 화면전환이 되지 않는 문제 #265
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Search.swift
  MiniVibe/MiniVibe/Views/Genre/GenreSection.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: bug, iOS🍎

#268 [FE] 장르 상세페이지 hotfix 수정
  client/components/organisms/CardLists/PlaylistCardList/PlaylistCardList.stories.tsx
  client/components/organisms/CardLists/PlaylistCardList/index.tsx
  client/pages/genre/sample.tsx
Labels: FE, Web

#269 [iOS] 재생바 UI를 바이브 앱과 유사하게 수정 #267
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
Labels: enhancement, iOS🍎

#270 [iOS] 탭바 아이콘을 눌러 화면 전환 시 이전에 네비게이션 된 화면이 남아있는 문제 #256
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
Labels: bug, iOS🍎

#272 Feat/model setting be
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db.ts
  server/src/models/Album.ts
  server/src/models/Artist.ts
  server/src/models/Genre.ts
  server/src/models/Magazine.ts
  server/src/models/News.ts
  server/src/models/Playlist.ts
  server/src/models/Track.ts
  server/src/models/User.ts
  server/src/routes/user.ts
  server/tsconfig.json
Labels: BE, Web

#275 [BE] 뉴스 리스트 조회 API 구현
  server/.eslintrc.js
  server/src/app.ts
  server/src/models/News.ts
  server/src/routes/index.ts
  server/src/routes/news/index.ts
  server/src/routes/news/news.controller.ts
  server/src/routes/users/index.ts
Labels: BE, Web

#276 [FE] player track info & Music player 구현
  client/components/atoms/Heart/Heart.stories.tsx
  client/components/atoms/Heart/Heart.tsx
  client/components/molecules/PlaylistDisplayButton/index.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/LyricModal/LyricModal.tsx
  client/components/organisms/MusicPlayer/MusicPlayer.stories.tsx
  client/components/organisms/MusicPlayer/PlayController/PlayController.stories.tsx
  client/components/organisms/MusicPlayer/PlayController/index.tsx
  client/components/organisms/MusicPlayer/PlayerTrackInfo/PlayerTrackInfo.stories.tsx
  client/components/organisms/MusicPlayer/PlayerTrackInfo/index.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/pages/_app.tsx
  client/pages/genre/sample.tsx
Labels: FE, Web

#290 [BE] 보관함 트랙 관련 API 구현
  server/src/routes/index.ts
  server/src/routes/library/index.ts
  server/src/routes/library/tracks/index.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
Labels: BE, Web

#284 [BE] 매거진 개별/ 리스트 조회 API 구현
  server/src/models/Track.ts
  server/src/routes/index.ts
  server/src/routes/magazines/index.ts
  server/src/routes/magazines/magazines.controller.ts
  server/src/routes/news/index.ts
Labels: BE, Web

#289 [FE] 플로팅 셀렉트 메뉴 구현
  client/components/atoms/Button/Button.stories.tsx
  client/components/atoms/Button/Button.styles.tsx
  client/components/atoms/Button/Button.tsx
  client/components/organisms/FloatingSelectMenu/FloatingSelectMenu.stories.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/pages/_app.tsx
Labels: FE, Web

#292 [FE] 플레이리스트 모달창 구현
  client/components/organisms/PlaylistModal/NewPlaylistButton/NewPlaylistButton.stories.tsx
  client/components/organisms/PlaylistModal/NewPlaylistButton/index.tsx
  client/components/organisms/PlaylistModal/PlaylistAddModal/PlaylistAddModal.stories.tsx
  client/components/organisms/PlaylistModal/PlaylistAddModal/index.tsx
  client/components/organisms/PlaylistModal/PlaylistModal.stories.tsx
  client/components/organisms/PlaylistModal/PlaylistRowCard/PlaylistRowCard.stories.tsx
  client/components/organisms/PlaylistModal/PlaylistRowCard/index.tsx
  client/components/organisms/PlaylistModal/index.tsx
Labels: FE, Web

#304 트랙 리스트, 개별 조회 API 구현
  server/src/routes/index.ts
  server/src/routes/tracks/index.ts
  server/src/routes/tracks/tracks.controller.ts
Labels: BE, Web

#307 앨범 개별/리스트 조회 API 구현
  server/src/routes/albums/albums.controller.ts
  server/src/routes/albums/index.ts
  server/src/routes/index.ts
Labels: BE, Web

#301 [BE] 아티스트 전체 조회/개별 조회 API 구현
  server/src/models/Track.ts
  server/src/routes/artists/artists.controller.ts
  server/src/routes/artists/index.ts
  server/src/routes/index.ts
Labels: BE, Web

#308 [BE] 보관함 아티스트 & 보관함 앨범 관련 api 구현
  server/src/models/User.ts
  server/src/routes/library/album/index.ts
  server/src/routes/library/album/library.album.controller.ts
  server/src/routes/library/artist/index.ts
  server/src/routes/library/artist/library.artist.controller.ts
  server/src/routes/library/index.ts
Labels: BE, Web

#312 [BE] 플레이리스트 관련 api(2) - 곡 추가/앨범추가/보관함 리스트 조회
  server/.eslintrc.js
  server/.prettierrc
  server/src/models/Playlist.ts
  server/src/models/User.ts
  server/src/routes/index.ts
  server/src/routes/library/index.ts
  server/src/routes/library/playlists/index.ts
  server/src/routes/library/playlists/library.playlists.controller.ts
  server/src/routes/playlists/index.ts
  server/src/routes/playlists/playlists.controller.ts
  server/src/routes/tracks/tracks.controller.ts
Labels: BE, Web

#314 Track 좋아요 필드 추가 / 기존 API track 부분 응답 수정 / query -> params로 통일
  server/src/models/Track.ts
  server/src/models/User.ts
  server/src/routes/albums/albums.controller.ts
  server/src/routes/artists/artists.controller.ts
  server/src/routes/library/album/index.ts
  server/src/routes/library/album/library.album.controller.ts
  server/src/routes/library/artist/index.ts
  server/src/routes/library/artist/library.artist.controller.ts
  server/src/routes/library/index.ts
  server/src/routes/library/tracks/index.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
  server/src/routes/magazines/magazines.controller.ts
  server/src/routes/playlists/playlists.controller.ts
  server/src/routes/tracks/tracks.controller.ts
Labels: BE, Web

#315 [BE] 보관함(플레이리스트) 좋아요 취소 API 구현
  server/src/routes/library/playlists/index.ts
  server/src/routes/library/playlists/library.playlists.controller.ts
Labels: BE, Web

#321 [BE] 믹스테잎 관련 api 구현 및 플레이리스트 관련 api 수정
  server/src/models/Playlist.ts
  server/src/routes/index.ts
  server/src/routes/library/index.ts
  server/src/routes/library/mixtapes/index.ts
  server/src/routes/library/mixtapes/library.mixtapes.controller.ts
  server/src/routes/mixtapes/index.ts
  server/src/routes/mixtapes/mixtapes.controller.ts
  server/src/routes/playlists/index.ts
  server/src/routes/playlists/playlists.controller.ts
Labels: BE, Web

#322 [FE & BE] 데이터 받아오는 방식 변경 & 각 페이지 더미 데이터 변경 & 아티스트 컨트롤러 수정 등
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.tsx
  client/components/molecules/ChartCard/ChartCard.styles.tsx
  client/components/molecules/ChartCard/ChartCard.tsx
  client/components/organisms/CardLists/ChartCardList/index.tsx
  client/components/organisms/CardLists/ContentsCardList/ContentsCardList.tsx
  client/components/organisms/CardLists/TrackRowList/TrackRowList.stories.tsx
  client/components/organisms/CardLists/TrackRowList/index.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MagazineCard/MagazineCard.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.stories.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.tsx
  client/interfaces/props.ts
  client/pages/album/sample.tsx
  client/pages/artist/sample.tsx
  client/pages/chart.tsx
  client/pages/genre/sample.tsx
  client/pages/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/pages/magazines.tsx
  client/pages/magazines/sample.tsx
  client/pages/mixtape/sample.tsx
  client/pages/playlist/sample.tsx
  client/pages/this-month.tsx
  client/pages/track/sample.tsx
  server/src/routes/artists/artists.controller.ts
Labels: BE, FE, Web

#324 [FE] 뮤직 플레이어 데이터 변경
  client/components/organisms/MusicPlayer/MusicPlayer.stories.tsx
  client/components/organisms/MusicPlayer/PlayerTrackInfo/index.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/pages/_app.tsx
Labels: FE, Web

#331 [FE] 투데이 페이지 데이터 api 연결 / api 유틸리티 함수 구현
  client/constants/apiUrl.ts
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/utils/apis.js
Labels: FE, Web

#332 [iOS] 이벤트 수집 부분 적용 #327, #330
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Chart.swift
  MiniVibe/MiniVibe/EventLogger/EventLogger.swift
  MiniVibe/MiniVibe/EventLogger/EventUseCase.swift
  MiniVibe/MiniVibe/EventLogger/TransitionLogModifier.swift
  MiniVibe/MiniVibe/EventLogger/ViewIdentifier.swift
  MiniVibe/MiniVibe/EventLogger/ViewLogger.swift
  MiniVibe/MiniVibe/Extensions/CGFloat+Constant.swift
  MiniVibe/MiniVibe/Extensions/EnvironmentValues+ImageCache.swift
  MiniVibe/MiniVibe/Extensions/Image+TrackRowConfigure.swift
  MiniVibe/MiniVibe/Extensions/View+dismissKeyboard.swift
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
  MiniVibe/MiniVibe/Models/Utils/ImageCache.swift
  MiniVibe/MiniVibe/Models/Utils/ImageLoader.swift
  MiniVibe/MiniVibe/Models/Utils/NetworkService.swift
  MiniVibe/MiniVibe/Resource/FavoritePlayList.json
  MiniVibe/MiniVibe/Resource/Magazines.json
  MiniVibe/MiniVibe/Resource/MyMixtape.json
  MiniVibe/MiniVibe/Resource/MyTastePlayList.json
  MiniVibe/MiniVibe/Resource/RecommandedAlbum.json
  MiniVibe/MiniVibe/Resource/RecommandedPlayList.json
  MiniVibe/MiniVibe/Resource/Stations.json
  MiniVibe/MiniVibe/ViewModels/MagazineViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerSliderView.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Search/Search.swift
  MiniVibe/MiniVibe/Views/Search/SearchBar.swift
  MiniVibe/MiniVibe/Views/Today/StationSection.swift
  MiniVibe/MiniVibe/Views/Today/StationStack.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: PairProgramming, enhancement, iOS🍎

#339 [FE/BE] 플레이리스트 상세 화면 구현 / 플레이리스트 상세 조회 시 연관된 아티스트 목록 반환
  client/interfaces/props.ts
  client/pages/index.tsx
  client/pages/playlist/[id].tsx
  client/pages/playlist/sample.tsx
  client/tsconfig.json
  client/utils/apis.js
  server/src/routes/playlists/playlists.controller.ts
  server/tsconfig.json
Labels: BE, Web

#344 [FE/BE] 앨범 상세 페이지 api 연결 / 앨범 상세 조회 api 수정
  client/pages/album/[id].tsx
  client/pages/album/sample.tsx
  server/src/routes/albums/albums.controller.ts
Labels: BE, Web

#349 [iOS] 믹스테잎, 아티스트 화면 API 연동 #81
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/EventLogger/ViewIdentifier.swift
  MiniVibe/MiniVibe/Models/Albums.swift
  MiniVibe/MiniVibe/Models/Artist.swift
  MiniVibe/MiniVibe/Models/Mixtape.swift
  MiniVibe/MiniVibe/Models/Track.swift
  MiniVibe/MiniVibe/Models/UseCases/ArtistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
  MiniVibe/MiniVibe/Models/UseCases/TodayUseCase.swift
  MiniVibe/MiniVibe/ViewModels/AlbumViewModel.swift
  MiniVibe/MiniVibe/ViewModels/ArtistSectionViewModel.swift
  MiniVibe/MiniVibe/ViewModels/ArtistViewModel.swift
  MiniVibe/MiniVibe/ViewModels/TodayViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistItem.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistThumbnail.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Menu/ArtistMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Library/LibraryArtistsView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#341 [FE] 유저 보관함 페이지 데이터 랜더링 구현
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/constants/apiUrl.ts
  client/interfaces/props.ts
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/utils/apis.js
  server/src/routes/library/index.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
Labels: FE, Web

#347 [FE] redux & redux-saga 세팅 및 예시 코드 작성
  client/package.json
  client/pages/_app.tsx
  client/reducers/index.ts
  client/reducers/musicPlayer.ts
  client/sagas/index.ts
  client/store/configureStore.ts
  client/stores/sample.ts
Labels: FE, Web

#350 [iOS] EnvironmentObject로 사용될 NowPlaying class 생성 #345
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
Labels: enhancement, iOS🍎

#351 [FE] 매거진, 트랙 상세 페이지 api 연결 / 아티스트 상세 조회 api 수정
  client/constants/apiUrl.ts
  client/pages/magazines/[id].tsx
  client/pages/magazines/main.tsx
  client/pages/track/[id].tsx
  server/src/routes/artists/artists.controller.ts
Labels: BE, FE, Web

#352 [iOS] TrackRow와 관련된 문제 fix
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Models/Track.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Today/MagazineView.swift
Labels: bug, iOS🍎

#353 [iOS] PlaylistView API 연동 #81
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Extensions/Image+TrackRowConfigure.swift
  MiniVibe/MiniVibe/Models/Playlists.swift
  MiniVibe/MiniVibe/Models/UseCases/PlaylistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/TodayUseCase.swift
  MiniVibe/MiniVibe/ViewModels/PlaylistViewModel.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayListMenu.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
Labels: enhancement

#359 [iOS] 플레이어 및 프리뷰 기능 구현 #349
  MiniVibe/.swiftlint.yml
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MiniVibe/MiniVibe/EventLogger/EventLogger.swift
  MiniVibe/MiniVibe/Extensions/EnvironmentValues+ImageCache.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Models/Utils/ImageCache.swift
  MiniVibe/MiniVibe/Models/Utils/ImageLoader.swift
  MiniVibe/MiniVibe/ViewModels/ArtistViewModel.swift
  MiniVibe/MiniVibe/ViewModels/SearchViewModel.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistItem.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistThumbnail.swift
  MiniVibe/MiniVibe/Views/Common/AsyncImage.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/Components/ThumbnailItem.swift
  MiniVibe/MiniVibe/Views/Common/Menu/ArtistMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuThumbnailButton.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailRow.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Profile/Article.swift
  MiniVibe/MiniVibe/Views/Search/Components/NewsItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/MagazineItem.swift
  MiniVibe/Podfile
  MiniVibe/Podfile.lock
Labels: bug, enhancement, iOS🍎

#363 CoreData를 활용한 이벤트 로그 저장 #361, #362
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/CoreData/Event.xcdatamodeld/Event.xcdatamodel/contents
  MiniVibe/MiniVibe/CoreData/Transition+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Transition+CoreDataProperties.swift
  MiniVibe/MiniVibe/EventLogger/EventLogView.swift
  MiniVibe/MiniVibe/EventLogger/EventLogViewModel.swift
  MiniVibe/MiniVibe/EventLogger/EventLogger.swift
  MiniVibe/MiniVibe/EventLogger/ViewIdentifier.swift
  MiniVibe/MiniVibe/Extensions/Date+timeStampFormat.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
Labels: enhancement, iOS🍎

#360 [FE] 유저 보관함 데이터 없을 경우 처리
  client/components/molecules/NoDataContainer/NoDataContainer.stories.tsx
  client/components/molecules/NoDataContainer/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  server/src/routes/library/album/library.album.controller.ts
Labels: FE, Web

#365 [iOS] 이벤트가 발생할 NowPlaying 관련 기능 구현 #348
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/EventLogger/EventUseCase.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Models/Track.swift
  MiniVibe/MiniVibe/Models/UseCases/AlbumUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/ArtistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
  MiniVibe/MiniVibe/Models/UseCases/PlaylistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/SearchUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/TodayUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/TrackUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/UseCaseError.swift
  MiniVibe/MiniVibe/Models/Utils/NetworkService.swift
  MiniVibe/MiniVibe/ViewModels/MagazineViewModel.swift
  MiniVibe/MiniVibe/ViewModels/SearchViewModel.swift
  MiniVibe/MiniVibe/ViewModels/TodayViewModel.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/ArtistMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuButton.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuThumbnailButton.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayListMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/MultiselectTabBar.swift
  MiniVibe/MiniVibe/Views/Common/MultiselectTabBarItems.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/TabbarButton.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailRow.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Search/GenreSection.swift
  MiniVibe/MiniVibe/Views/Today/MagazineView.swift
Labels: enhancement, iOS🍎

#364 [FE] context를 통한 component Id/ data 전달
  client/components/organisms/CardLists/ContentsCardList/ContentsCardList.tsx
  client/components/organisms/CardLists/MagazineList/MagazineList.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/CardLists/TrackRowList/index.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/constants/identifier.ts
  client/pages/_app.tsx
  client/pages/album/[id].tsx
  client/pages/artist/[id].tsx
  client/pages/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/pages/magazine/[id].tsx
  client/pages/magazines/[id].tsx
  client/pages/playlist/[id].tsx
  client/pages/track/[id].tsx
  client/utils/context/ComponentInfoContext.ts
  client/utils/context/ComponentInfoWrapper.tsx
Labels: FE, Web

#366 [FE] 빌드 시 발생하는 오류 수정
  client/components/atoms/Button/Button.styles.tsx
  client/components/atoms/IconButton/IconButton.tsx
  client/components/atoms/Image/Image.styles.tsx
  client/components/atoms/Image/Image.tsx
  client/components/atoms/Input/Input.styles.tsx
  client/components/atoms/Input/Input.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.stories.tsx
  client/components/molecules/ChartCard/ChartCard.stories.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.stories.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/molecules/DropdownMenu/index.tsx
  client/components/molecules/PlaylistDisplayButton/PlaylistButton.stories.tsx
  client/components/molecules/PlaylistDisplayButton/index.tsx
  client/components/molecules/SearchInput/SearchInput.tsx
  client/components/molecules/SlideNextButton/index.tsx
  client/components/molecules/SlidePrevButton/index.tsx
  client/components/molecules/TrackCard/TrackCard.stories.tsx
  client/components/molecules/TrackInfo/TrackInfo.stories.tsx
  client/components/molecules/TrackInfo/index.tsx
  client/components/molecules/TrackPlayButton/TrackPlayButton.stories.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/CardLists/StationCardList/StationCardList.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/interfaces/props.ts
Labels: FE, Web

#368 [FE] 클릭 이벤트 수집
  client/components/atoms/A/A.tsx
  client/components/atoms/MenuLink/MenuLink.tsx
  client/hooks/useClickEventLog.ts
  client/reducers/index.ts
  client/reducers/user.ts
  client/utils/eventLogger.ts
Labels: FE, Web

#371 [FE] 플로팅 셀렉트 메뉴와 체크박스 연결 & 뮤직 플레이어 일부 기능 구현
  client/components/atoms/CheckBox/index.tsx
  client/components/molecules/PlayControllerButtons/index.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/components/organisms/MusicPlayer/PlayController/index.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/reducers/index.ts
  client/reducers/musicPlayer.ts
  client/reducers/selectedTrack.ts
  client/tsconfig.json
Labels: FE, Web

#374 [FE] 화면 전환 이벤트 수집
  client/hooks/sample.ts
  client/hooks/useClickEventLog.ts
  client/hooks/useTransitionEventLog.ts
  client/pages/_app.tsx
  client/utils/apis.js
Labels: FE, Web

#372 [FE] 드롭다운메뉴 기능 & 좋아요 및 좋아요 취소
  client/components/atoms/CheckBox/CheckBox.stories.tsx
  client/components/atoms/CheckBox/index.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/molecules/DropdownMenu/index.tsx
  client/components/organisms/ArtistHeader/ArtistHeader.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.styles.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/components/organisms/MusicPlayer/PlayerTrackInfo/index.tsx
  client/components/organisms/PlaylistModal/PlaylistRowCard/index.tsx
  client/components/organisms/PlaylistModal/index.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/constants/apiUrl.ts
  client/constants/dropDownMenu.ts
  client/hooks/useDropDownAction.ts
  client/interfaces/props.ts
  client/utils/apis.js
  server/src/routes/library/album/library.album.controller.ts
  server/src/routes/library/artist/library.artist.controller.ts
  server/src/routes/library/playlists/library.playlists.controller.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
  server/src/routes/playlists/index.ts
  server/src/routes/playlists/playlists.controller.ts
Labels: FE, Web

#375 [FE] 트랙 보관함에서 전체재생 기능 구현 & 플로팅 셀렉트 메뉴 오류 수정
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/components/organisms/Library/LibraryHeader/LibraryHeader.tsx
  client/pages/library/tracks.tsx
Labels: FE, Web

#383 [iOS] 화면 전환 이벤트 수집, 저장, 출력 #379
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MiniVibe/MiniVibe/Chart.swift
  MiniVibe/MiniVibe/EventLogger/ComponentId.swift
  MiniVibe/MiniVibe/EventLogger/TransitionLogModifier.swift
  MiniVibe/MiniVibe/EventLogger/ViewIdentifier.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/Views/Album/AlbumSection.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Library/LibraryAlbumsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryArtistsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryPlayListView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Search/Components/NewsItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineSection.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today/StationSection.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#384 [iOS] 이슈번호에 해당하는 이벤트 수집, 저장, 출력 #380 #381 #382
  MiniVibe/MiniVibe/EventLogger/EventLogger.swift
  MiniVibe/MiniVibe/EventLogger/Events/EngagementLog.swift
  MiniVibe/MiniVibe/EventLogger/TransitionLogModifier.swift
  MiniVibe/MiniVibe/Info.plist
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
Labels: enhancement, iOS🍎

#391 [iOS] 좋아요 이벤트 저장, 수집, 출력 #387
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/EventLogger/EventLogger.swift
  MiniVibe/MiniVibe/EventLogger/Events/LikeLog.swift
  MiniVibe/MiniVibe/EventLogger/TransitionLogModifier.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/ViewModels/AlbumViewModel.swift
  MiniVibe/MiniVibe/ViewModels/PlaylistViewModel.swift
  MiniVibe/MiniVibe/ViewModels/TrackViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumSection.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuThumbnailButton.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayListMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Library/LibraryAlbumsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryPlayListView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Search/Components/NewsItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineView.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
Labels: enhancement, iOS🍎

#392 [BE] 이벤트 모델 인터페이스, 스키마 정의/ 이벤트 로그 API 구현
  server/src/models/Event.ts
  server/src/models/PlayEvent.ts
  server/src/routes/events/events.controller.ts
  server/src/routes/events/index.ts
  server/src/routes/index.ts
  server/src/routes/playEvents/index.ts
  server/src/routes/playEvents/playEvents.controller.ts
  server/src/types/event.ts
Labels: BE, Web

#394 [FE] 빌드 오류 해결 & 플로팅 셀렉트 메뉴 오류 수정 & 앨범 오류 수정 & getServerSideProps로 수정 등
  client/components/atoms/CheckBox/CheckBox.stories.tsx
  client/components/atoms/CheckBox/index.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/molecules/DropdownMenu/index.tsx
  client/components/molecules/ProgressBar/index.tsx
  client/components/organisms/CardLists/ContentsCardList/ContentsCardList.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/components/organisms/Cards/PlayerTrackCard/PlayerTrackCard.stories.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/components/organisms/Cards/StationCard/StationCard.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/ContentsButtonGroup/index.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/components/organisms/Library/LibraryHeader/LibraryHeader.stories.tsx
  client/components/organisms/LyricModal/LyricModal.stories.tsx
  client/components/organisms/LyricModal/LyricModal.tsx
  client/components/organisms/MusicPlayer/MusicPlayer.stories.tsx
  client/components/organisms/MusicPlayer/PlayController/index.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/hooks/useDropDownAction.ts
  client/interfaces/props.ts
  client/pages/_app.tsx
  client/pages/magazines.tsx
  client/pages/this-month.tsx
  client/reducers/index.ts
  client/sagas/index.ts
  client/store/configureStore.ts
Labels: FE, Web, bug

#407 프로젝트 구조 개선, NetworkService 테스트코드 수정 #403, #404
  MiniVibe/MiniVibe/Models/UseCases/AlbumUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/ArtistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/PlaylistUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/SearchUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/TodayUseCase.swift
  MiniVibe/MiniVibe/Models/UseCases/TrackUseCase.swift
  MiniVibe/MiniVibe/Models/Utils/NetworkService.swift
  MiniVibe/MiniVibe/ViewModels/AlbumViewModel.swift
  MiniVibe/MiniVibe/ViewModels/ArtistSectionViewModel.swift
  MiniVibe/MiniVibe/ViewModels/ArtistViewModel.swift
  MiniVibe/MiniVibe/ViewModels/PlaylistViewModel.swift
  MiniVibe/MiniVibe/ViewModels/SearchViewModel.swift
  MiniVibe/MiniVibe/ViewModels/TodayViewModel.swift
  MiniVibe/MiniVibe/ViewModels/TrackViewModel.swift
  MiniVibe/MiniVibeTests/MiniVibeTests.swift
  MiniVibe/MiniVibeTests/NetworkError+Equatable.swift
Labels: iOS🍎

#413 [iOS] EventLogKit을 활용해 이벤트 수집, 저장, 출력 #401
  EventLogKit/EventLogKit/EventLogger.swift
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/EventLogger/EventLogViewModel.swift
  MiniVibe/MiniVibe/EventLogger/LocalEventStorage.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
Labels: enhancement, iOS🍎

#415 [iOS] 앱 종류 이후에도 Upnext의 최종상태 restore를 위한 Core Data 사용 #399
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Chart.swift
  MiniVibe/MiniVibe/CoreData/LatestUpnext+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/TrackInfoData.swift
  MiniVibe/MiniVibe/CoreData/User.xcdatamodeld/User.xcdatamodel/contents
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/Models/Track.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
  MiniVibe/MiniVibe/Models/UseCases/TrackUseCase.swift
  MiniVibe/MiniVibe/Views/Album/AlbumSection.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibe/Views/Common/Menu/MenuThumbnailButton.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayListMenu.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Library/LibraryAlbumsView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryPlayListView.swift
  MiniVibe/MiniVibe/Views/Library/LibrarySongsView.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Profile/Article.swift
  MiniVibe/MiniVibe/Views/Search/Components/NewsItem.swift
  MiniVibe/MiniVibe/Views/Search/GenreSection.swift
  MiniVibe/MiniVibe/Views/Search/SearchView.swift
  MiniVibe/MiniVibe/Views/Today/Components/PreviewItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineView.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today/StationList.swift
  MiniVibe/MiniVibeTests/MiniVibeTests.swift
Labels: enhancement, iOS🍎

#416 [iOS] imagePlaceholder, UI 수정
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistItem.swift
  MiniVibe/MiniVibe/Views/Artist/Components/ArtistThumbnail.swift
  MiniVibe/MiniVibe/Views/Common/Components/PlaylistAlbumInfo.swift
  MiniVibe/MiniVibe/Views/Common/Components/ThumbnailItem.swift
  MiniVibe/MiniVibe/Views/Common/Menu/Components/MenuAlbumImage.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailRow.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/Components/TrackRowImage.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibe/Views/Profile/Article.swift
  MiniVibe/MiniVibe/Views/Search/Components/NewsItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/MagazineItem.swift
Labels: bug, iOS🍎

#412 [FE] 이벤트 로거 api 연결 / apis 함수 리팩토링 / 검색 이벤트 수집
  client/components/atoms/Input/Input.tsx
  client/components/molecules/DropdownMenu/index.tsx
  client/components/molecules/SearchInput/SearchInput.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/constants/apiUrl.ts
  client/hooks/useClickEventLog.ts
  client/hooks/useDropDownAction.ts
  client/hooks/useSearchEventLog.ts
  client/hooks/useTransitionEventLog.ts
  client/interfaces/props.ts
  client/pages/index.tsx
  client/pages/magazine/[id].tsx
  client/pages/playlist/[id].tsx
  client/utils/apis.js
  client/utils/eventLogger.ts
Labels: FE, Web

#421 [iOS] UseCase 테스트코드 작성 #404 Open
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibeTests/AlbumUseCaseTests.swift
  MiniVibe/MiniVibeTests/ArtistsUseCaseTests.swift
  MiniVibe/MiniVibeTests/Extensions/AlbumExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/ArtistsExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/MagazineExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/MixtapeExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/NetworkError+Equatable.swift
  MiniVibe/MiniVibeTests/Extensions/NewsExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/PlaylistExtensions.swift
  MiniVibe/MiniVibeTests/Extensions/TrackExtensions.swift
  MiniVibe/MiniVibeTests/Mock/MockNetworkServices.swift
  MiniVibe/MiniVibeTests/NetworkServiceTests.swift
  MiniVibe/MiniVibeTests/PlaylistUseCaseTests.swift
  MiniVibe/MiniVibeTests/SearchUseCaseTests.swift
  MiniVibe/MiniVibeTests/TodayUseCaseTests.swift
  MiniVibe/MiniVibeTests/TrackUseCaseTests.swift
Labels: iOS🍎, test

#427 [iOS] TodayViewModel 구조 개선, 테스트 코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ViewModels/TodayViewModel.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
  MiniVibe/MiniVibeTests/Mock/MockTodayUseCase.swift
  MiniVibe/MiniVibeTests/TodayViewModelTests.swift
Labels: iOS🍎, test

#422 [FE] 좋아요/ 좋아요 취소 이벤트 수집
  client/components/molecules/DropdownMenu/index.tsx
  client/components/organisms/ArtistHeader/ArtistHeader.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/hooks/useDropDownAction.ts
  client/hooks/useLikeEventLog.ts
  client/pages/index.tsx
Labels: FE, Web

#424 [FE & BE] 로그인 에러 수정
  client/components/atoms/A/A.tsx
  client/components/atoms/MenuLink/MenuLink.tsx
  client/components/organisms/HeaderSideBar/index.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/constants/actions.ts
  client/constants/apiUrl.ts
  client/interfaces/props.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/reducers/index.ts
  client/reducers/user.ts
  client/sagas/index.ts
  client/sagas/musicPlayer.ts
  client/sagas/user.ts
  client/store/configureStore.ts
  client/utils/apis.js
  client/utils/cookies.ts
  server/package-lock.json
  server/src/app.ts
  server/src/routes/library/mixtapes/library.mixtapes.controller.ts
  server/src/routes/library/tracks/index.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
  server/src/routes/users/index.ts
Labels: BE, FE, Web, bug

#426 [FE] UpNextChange 이벤트 수집
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/constants/events.ts
  client/hooks/useUpNextChangeEventLog.ts
  client/utils/apis.js
  client/utils/eventLogger.ts
Labels: FE, Web

#429 AlbumViewModel 구조 개선, 테스트 코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ViewModels/AlbumViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Common/Menu/AlbumMenu.swift
  MiniVibe/MiniVibeTests/AlbumViewModelTests.swift
  MiniVibe/MiniVibeTests/Extensions/AlbumViewModelExtensions.swift
  MiniVibe/MiniVibeTests/Mock/MockAlbumUseCase.swift
  MiniVibe/MiniVibeTests/Mock/MockEventLogger.swift
Labels: iOS🍎, test

#428 [iOS] TrackViewModel 구조 개선, 테스트 코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Models/NowPlaying.swift
  MiniVibe/MiniVibe/ViewModels/TrackViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListView.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibeTests/Mock/MockTrackUseCase.swift
  MiniVibe/MiniVibeTests/TrackViewModelTests.swift
Labels: iOS🍎, test

#436 [iOS] ArtistSectionViewModel 테스트코드 작성 #419 #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ViewModels/ArtistSectionViewModel.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibeTests/ArtistSectionViewModelTests.swift
  MiniVibe/MiniVibeTests/Mock/MockArtistSectionUseCase.swift
Labels: iOS🍎, test

#438 [iOS] ArtistViewModel 구조 개선, 테스트 코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ViewModels/ArtistViewModel.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistSection.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Library/LibraryArtistsView.swift
  MiniVibe/MiniVibeTests/ArtistViewModelTests.swift
  MiniVibe/MiniVibeTests/Mock/MockArtistSectionUseCase.swift
Labels: iOS🍎, test

#439 [iOS] SearchViewModel 구조 개선, 테스트코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ViewModels/SearchViewModel.swift
  MiniVibe/MiniVibe/Views/Search/SearchBar.swift
  MiniVibe/MiniVibe/Views/Search/SearchView.swift
  MiniVibe/MiniVibeTests/Mock/MockSearchUseCase.swift
  MiniVibe/MiniVibeTests/SearchViewModelTests.swift
Labels: iOS🍎, test

#431 [BE] 인증 관련 동작 에러 수정
  client/package-lock.json
  client/utils/apis.js
  server/src/routes/auth/index.ts
  server/src/routes/index.ts
  server/src/routes/playlists/index.ts
  server/src/routes/users/index.ts
Labels: BE, Web, bug

#441 [iOS] MainTabViewModel 구조 개선 및 테스트코드 작성 #419, #420
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/1024.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/152.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/20.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/29.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/40-1.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/40-2.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/40.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/58.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/60.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/76.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/80.png
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/Contents.json
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/ViewModels/MainTabViewModel.swift
  MiniVibe/MiniVibeTests/MainTabViewModelTests.swift
Labels: iOS🍎, test

#442 [FE&BE] 쿠키로 요청 보내도록 수정 & 플레이리스트 상세에서 유저 아이디 쓰도록 수정
  client/pages/album/[id].tsx
  client/pages/artist/[id].tsx
  client/pages/index.tsx
  client/pages/magazine/[id].tsx
  client/pages/playlist/[id].tsx
  client/pages/this-month.tsx
  client/pages/track/[id].tsx
  client/utils/apis.js
  server/src/routes/playlists/playlists.controller.ts
Labels: BE, FE, Web, bug

#444 [FE] 비로그인 시 상세 페이지 404 에러 해결
  client/utils/apis.js
Labels: FE, Web, bug

#446 [iOS] EventLogKit을 활용해 수집한 이벤트를 서버에 전송 #418
  EventLogKit/EventLogKit/EventLogger.swift
  EventLogKit/EventLogKit/StorageTypes.swift
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe.xcodeproj/xcshareddata/xcschemes/MiniVibe.xcscheme
  MiniVibe/MiniVibe/EventLogger/Events/EngagementLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/LikeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/MoveTrackLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/PlayLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SaveLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SearchLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/ShareLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SubscribeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/Transitions.swift
  MiniVibe/MiniVibe/EventLogger/Events/UpnextChangeLog.swift
  MiniVibe/MiniVibe/EventLogger/ServerEventStorage.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
Labels: iOS🍎, test

#451 [iOS] NowPlaying 구조 개선, 재생관련 이벤트 수집, 테스트코드 작성 #443, #447
  EventLogKit/EventLogKit/EventLogType.swift
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/CoreData/PlayerDataManager.swift
  MiniVibe/MiniVibe/EventLogger/Events/CustomEventLogType.swift
  MiniVibe/MiniVibe/EventLogger/Events/EngagementLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/LikeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/MoveTrackLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/PlayLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SaveLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SearchLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/ShareLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SubscribeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/Transitions.swift
  MiniVibe/MiniVibe/EventLogger/Events/UpnextChangeLog.swift
  MiniVibe/MiniVibe/EventLogger/LocalEventStorage.swift
  MiniVibe/MiniVibe/MainTab.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/ViewModels/NowPlayingViewModel.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionA.swift
  MiniVibe/MiniVibe/Views/Common/Menu/PlayerMenu.swift
  MiniVibe/MiniVibe/Views/Common/MultiselectTabBar.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/TabbarButton.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowA.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowC.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowD.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/TrackRowE.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerControls.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerHeader.swift
  MiniVibe/MiniVibe/Views/Player/Components/PlayerThumbnail.swift
  MiniVibe/MiniVibe/Views/Player/Lyrics.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Player/PlayerView.swift
  MiniVibe/MiniVibe/Views/Player/UpNextList.swift
  MiniVibe/MiniVibeTests/Mock/MockPlayerDataManager.swift
  MiniVibe/MiniVibeTests/NowPlayingViewModelTests.swift
Labels: enhancement, iOS🍎, test

#448 로그인 오류 수정
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/constants/apiUrl.ts
  client/pages/album/[id].tsx
  client/pages/artist/[id].tsx
  client/pages/index.tsx
  client/pages/library/albums.tsx
  client/pages/library/artists.tsx
  client/pages/library/mixtapes.tsx
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/pages/magazine/[id].tsx
  client/pages/playlist/[id].tsx
  client/pages/track/[id].tsx
  client/utils/apis.js
  client/utils/cookies.ts
  server/src/app.ts
  server/src/middlewares/auth.ts
  server/src/routes/auth/auth.controller.ts
  server/src/routes/auth/index.ts
  server/src/routes/index.ts
  server/src/routes/library/tracks/index.ts
  server/src/routes/library/tracks/library.tracks.controller.ts
  server/src/routes/playlists/index.ts
  server/src/routes/users/index.ts
  server/src/routes/users/users.controller.ts
Labels: FE, Web

#456 [iOS] CoreData에 저장된 데이터를 지울 때 런타임 에러 #455
  EventLogKit/EventLogKit/EventLogger.swift
  EventLogKit/EventLogKit/StorageTypes.swift
  MiniVibe/MiniVibe/EventLogger/ServerEventStorage.swift
Labels: bug, iOS🍎

#457 [iOS] 미완성 뷰 연결하기 #453
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Mixtape/MixtapeSection.swift
  MiniVibe/MiniVibe/Views/PlayList/PlayListSection.swift
  MiniVibe/MiniVibe/Views/Search/GenreSection.swift
  MiniVibe/MiniVibe/Views/Today/Components/PreviewItem.swift
  MiniVibe/MiniVibe/Views/Today/Components/StationItem.swift
  MiniVibe/MiniVibe/Views/Today/PreviewSection.swift
  MiniVibe/MiniVibe/Views/Today/StationList.swift
  MiniVibe/MiniVibe/Views/Today/StationStack.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
Labels: enhancement, iOS🍎

#454 [FE] 각 페이지에서 보관함 저장(좋아요), 내 플레이리스트에 추가 에러 수정
  client/components/atoms/Button/AddButton.tsx
  client/components/atoms/CheckBox/index.tsx
  client/components/atoms/Heart/Heart.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/molecules/DropdownMenu/index.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/components/organisms/Cards/TrackRowCard/TrackRowCard.styles.tsx
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/hooks/useDropDownAction.ts
  client/interfaces/props.ts
  client/pages/this-month.tsx
  client/utils/apis.js
  server/src/app.ts
  server/src/routes/albums/albums.controller.ts
  server/src/routes/artists/artists.controller.ts
  server/src/routes/playlists/playlists.controller.ts
Labels: BE, FE, Web, bug

#445 [FE] play now 버튼 기능 구현 & 키 값 설정 등
  client/components/atoms/IconButton/IconButton.tsx
  client/components/atoms/Image/Image.styles.tsx
  client/components/atoms/Image/Image.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.stories.tsx
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/molecules/PlayButton/PlayButton.stories.tsx
  client/components/molecules/PlayButton/PlayButton.tsx
  client/components/organisms/ArtistHeader/ArtistHeader.tsx
  client/components/organisms/CardListContainer/CardListContainer.tsx
  client/components/organisms/CardLists/ContentsCardList/ContentsCardList.tsx
  client/components/organisms/CardLists/MagazineList/MagazineList.tsx
  client/components/organisms/CardLists/PlayerTrackList/index.tsx
  client/components/organisms/CardLists/TrackRowList/index.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MagazineCard/MagazineCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/components/organisms/Cards/StationCard/StationCard.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.stories.tsx
  client/components/organisms/Library/LibraryCardList/LibraryCardList.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.stories.tsx
  client/interfaces/props.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/magazine/[id].tsx
  client/reducers/user.ts
  client/sagas/user.ts
  client/utils/apis.js
Labels: FE, Web, bug

#450 [FE] 뮤직 플레이어 기능 구현: 특정곡 바로 재생, 특정곡 삭제, 로직 변경
  client/components/molecules/TrackInfo/index.tsx
  client/components/molecules/TrackPlayButton/index.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/components/organisms/MusicPlayer/PlayController/index.tsx
  client/components/organisms/MusicPlayer/PlayerTrackInfo/index.tsx
  client/components/organisms/MusicPlayer/index.tsx
  client/reducers/musicPlayer.ts
  client/utils/apis.js
Labels: FE, Web, bug, enhancement

#458 [FE] 뮤직 플레이어 프로그레스바 및 플레이타임 표시 관련 기능 구현 & 이달의 노래 아티스트 데이터 주입
  client/components/atoms/Input/Input.styles.tsx
  client/components/atoms/Playtime/index.tsx
  client/components/molecules/PlayControllerButtons/index.tsx
  client/components/molecules/ProgressBar/index.tsx
  client/constants/actions.ts
  client/pages/library/playlists.tsx
  client/pages/library/tracks.tsx
  client/pages/this-month.tsx
  client/reducers/musicPlayer.ts
  client/sagas/musicPlayer.ts
  client/utils/api.js
Labels: FE, Web

#463 [iOS] 차트 화면 수정 및 테스트코드 작성 #133
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe.xcodeproj/xcshareddata/xcschemes/MiniVibeTests.xcscheme
  MiniVibe/MiniVibe/Chart.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Models/UseCases/ChartsUseCase.swift
  MiniVibe/MiniVibe/ViewModels/ChartsViewModel.swift
  MiniVibe/MiniVibe/ViewModels/NowPlayingViewModel.swift
  MiniVibe/MiniVibe/Views/Album/AlbumView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistAlbumGridView.swift
  MiniVibe/MiniVibe/Views/Artist/ArtistView.swift
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSections/ChartSectionB.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/Components/TrackRowInfo.swift
  MiniVibe/MiniVibe/Views/Today/MagazineView.swift
  MiniVibe/MiniVibeTests/ChartUseCaseTests.swift
  MiniVibe/MiniVibeTests/ChartsViewModelTests.swift
  MiniVibe/MiniVibeTests/Mock/MockChartsUseCase.swift
  MiniVibe/MiniVibeTests/Mock/MockEventLogger.swift
  MiniVibe/MiniVibeTests/NowPlayingViewModelTests.swift
Labels: iOS🍎, test

#461 [FE&BE] 어드민 페이지 구현
  client/components/organisms/HeaderSideBar/HeaderSideBar.styles.tsx
  client/components/organisms/HeaderSideBar/index.tsx
  client/interfaces/eventProps.ts
  client/pages/admin.tsx
  server/src/routes/events/events.controller.ts
  server/src/routes/events/index.ts
  server/src/routes/playEvents/index.ts
  server/src/routes/playEvents/playEvents.controller.ts
Labels: BE, FE, Web, enhancement

#462 [FE] upNextChnage 이벤트, playNow 이벤트 수집
  client/components/molecules/PlayButton/PlayButton.tsx
  client/components/molecules/PlayControllerButtons/index.tsx
  client/components/molecules/TrackPlayButton/index.tsx
  client/components/organisms/Cards/PlayerTrackCard/index.tsx
  client/components/organisms/DetailHeader/index.tsx
  client/components/organisms/FloatingSelectMenu/index.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/hooks/usePlayNowEventLog.ts
  client/hooks/useUpNextChangeEventLog.ts
  client/interfaces/props.ts
  client/pages/magazine/[id].tsx
  server/src/models/PlayEvent.ts
  server/src/types/event.ts
Labels: FE, Web

#468 [iOS] 보관함 좋아요 곡 목록 구현 및 테스트 #467
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/Models/UseCases/EndPoint.swift
  MiniVibe/MiniVibe/Models/UseCases/LibraryUseCase.swift
  MiniVibe/MiniVibe/ViewModels/LibraryViewModel.swift
  MiniVibe/MiniVibe/Views/Common/TrackRows/Components/TrackRowInfo.swift
  MiniVibe/MiniVibeTests/LibraryUseCaseTests.swift
  MiniVibe/MiniVibeTests/LibraryViewModelTests.swift
  MiniVibe/MiniVibeTests/Mock/LibraryUseCase.swift
Labels: enhancement, iOS🍎, test

#470 [BE] 이벤트 서버 분리
  client/constants/apiUrl.ts
  eventSever/.eslintrc.js
  eventSever/.prettierrc
  eventSever/package-lock.json
  eventSever/package.json
  eventSever/src/app.ts
  eventSever/src/db.ts
  eventSever/src/models/Event.ts
  eventSever/src/routes/events/events.controller.ts
  eventSever/src/routes/events/index.ts
  eventSever/src/routes/index.ts
  eventSever/src/types/event.ts
  eventSever/tsconfig.json
Labels: BE, Web

#471 [FE] 매거진 드롭다운 동작 수정
  client/components/molecules/ContentsThumbnail/ContentsThumbnail.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/interfaces/props.ts
Labels: FE, Web

#466 [FE&BE] 로컬 로그인
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/constants/apiUrl.ts
  client/constants/identifier.ts
  client/package-lock.json
  client/package.json
  client/pages/login/index.tsx
  server/package-lock.json
  server/package.json
  server/src/routes/auth/auth.controller.ts
  server/src/routes/auth/index.ts
  server/src/routes/auth/passport/local-strategy.ts
  server/src/routes/auth/passport/naver-strategy.ts
  server/src/routes/auth/passport/passport-init.ts
Labels: BE, FE, Web

#464 [FE] storybook 오류 수정
  client/.storybook/preview.js
  client/components/molecules/DropdownMenu/index.tsx
  client/components/molecules/PlayButton/PlayButton.stories.tsx
  client/components/molecules/PlayButton/PlayButton.tsx
  client/components/organisms/ArtistHeader/ArtistHeader.tsx
  client/components/organisms/Cards/TrackRowCard/index.tsx
  client/components/organisms/HeaderButtonGroup/index.tsx
  client/components/organisms/PlaylistModal/PlaylistAddModal/index.tsx
  client/hooks/useDropDownAction.ts
  client/utils/eventLogger.ts
Labels: bug

#472 [BE&FE] fix: 이벤트 서버 & 어드민 페이지 오류 수정
  client/interfaces/eventProps.ts
  client/pages/admin.tsx
  eventSever/src/models/PlayEvent.ts
  eventSever/src/routes/index.ts
  eventSever/src/routes/playEvents/index.ts
  eventSever/src/routes/playEvents/playEvents.controller.ts
  eventSever/src/types/event.ts
  server/src/routes/events/events.controller.ts
  server/src/routes/events/index.ts
  server/src/routes/index.ts
Labels: BE, FE, Web, bug

#473 [FE&BE] 오류 수정
  client/components/organisms/HeaderButtonGroup/HeaderButtonGroup.stories.tsx
  client/pages/admin.tsx
  client/pages/login/index.tsx
  client/sagas/user.ts
  client/utils/apis.js
Labels: FE, Web, bug

#474 play 이벤트 수집
  client/components/molecules/PlayControllerButtons/index.tsx
  client/hooks/usePlayEventLog.ts
Labels: FE, Web

#475 [FE&BE] 회원가입 기능 구현
  client/components/atoms/Button/Button.tsx
  client/constants/actions.ts
  client/constants/identifier.ts
  client/hooks/useInput.ts
  client/pages/join.tsx
  client/pages/login/index.tsx
  client/reducers/user.ts
  client/sagas/user.ts
  server/package.json
  server/src/routes/auth/auth.controller.ts
  server/src/routes/auth/passport/local-strategy.ts
  server/src/routes/users/index.ts
  server/src/routes/users/users.controller.ts
Labels: BE, FE, Web

#482 [iOS] 보관함 화면에서 곡에대한 메뉴 화면이 정상적으로 동작하지 않던 문제 해결
  MiniVibe/MiniVibe/Library.swift
  MiniVibe/MiniVibe/ViewModels/LibraryViewModel.swift
  MiniVibe/MiniVibeTests/LibraryViewModelTests.swift
Labels: bug, iOS🍎

#479 차트 페이지 데이터 서버로부터 받아오도록 수정
  client/components/molecules/GenreCard/GenreCard.tsx
  client/components/organisms/CardLists/GenreCardList/index.tsx
  client/constants/apiUrl.ts
  client/pages/chart.tsx
  client/utils/color.ts
  server/package-lock.json
  server/src/routes/albums/albums.controller.ts
  server/src/routes/chart/chart.controller.ts
  server/src/routes/chart/index.ts
  server/src/routes/genres/genres.controller.ts
  server/src/routes/genres/index.ts
  server/src/routes/index.ts
Labels: BE, FE, Web

#480 로그아웃 기능 , 로컬 로그인 오류 수정
  client/components/molecules/DropdownMenu/index.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/pages/login/index.tsx
  server/src/routes/auth/auth.controller.ts
  server/src/routes/auth/passport/local-strategy.ts
Labels: BE, FE, Web

#481 [iOS] Feat: 기기가 와이파이에 연결되는 시점에 로컬에 저장된 로그 전송, 서버에 저장된 로그 목록 표시화면 구현 #465
  EventLogKit/EventLogKit/EventLogType.swift
  EventLogKit/EventLogKit/EventLogger.swift
  EventLogKit/EventLogKit/StorageTypes.swift
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/CoreData/Engagement+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Event.xcdatamodeld/Event.xcdatamodel/contents
  MiniVibe/MiniVibe/CoreData/Like+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/MoveTrack+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Play+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/PlayerDataManager.swift
  MiniVibe/MiniVibe/CoreData/Save+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Search+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Share+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Subscribe+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/Transition+CoreDataClass.swift
  MiniVibe/MiniVibe/CoreData/UpnextChange+CoreDataClass.swift
  MiniVibe/MiniVibe/EventLogger/EventEndPoint.swift
  MiniVibe/MiniVibe/EventLogger/EventLogResponse.swift
  MiniVibe/MiniVibe/EventLogger/EventLogUseCase.swift
  MiniVibe/MiniVibe/EventLogger/EventLogView.swift
  MiniVibe/MiniVibe/EventLogger/EventLogViewModel.swift
  MiniVibe/MiniVibe/EventLogger/Events/CustomEventLogType.swift
  MiniVibe/MiniVibe/EventLogger/Events/EngagementLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/EventPrintable.swift
  MiniVibe/MiniVibe/EventLogger/Events/LikeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/MoveTrackLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/PlayLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SaveLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SearchLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/ShareLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/SubscribeLog.swift
  MiniVibe/MiniVibe/EventLogger/Events/Transitions.swift
  MiniVibe/MiniVibe/EventLogger/Events/UpnextChangeLog.swift
  MiniVibe/MiniVibe/EventLogger/LocalEventStorage.swift
  MiniVibe/MiniVibe/EventLogger/ServerEventStorage.swift
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Player/Player.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
  MiniVibe/MiniVibeTests/LocalEventStorageTests.swift
Labels: enhancement, iOS🍎

#483 [FE] addToUpNext 오류 수정, playingStatus와 재생 버튼 연결
  client/components/molecules/PlayControllerButtons/index.tsx
  client/reducers/musicPlayer.ts
  client/sagas/musicPlayer.ts
Labels: FE, Web, bug

#485 [FE] 차트 카드 재생 & 트랙 한 곡 재생 시 발생하는 버그 수정
  client/components/atoms/Input/Input.tsx
  client/components/molecules/ChartCard/ChartCard.tsx
  client/components/molecules/GenreCard/GenreCard.stories.tsx
  client/components/organisms/CardLists/GenreCardList/GenreCardList.stories.tsx
  client/components/organisms/CardLists/GenreCardList/index.tsx
  client/components/organisms/PlaylistModal/PlaylistAddModal/PlaylistAddModal.stories.tsx
  client/components/organisms/PlaylistModal/PlaylistAddModal/index.tsx
  client/components/organisms/PlaylistModal/PlaylistModal.stories.tsx
  client/interfaces/props.ts
  client/reducers/index.ts
  client/reducers/musicPlayer.ts
  client/reducers/playlist.ts
  client/reducers/selectedTrack.ts
  client/reducers/user.ts
  server/src/routes/chart/chart.controller.ts
Labels: BE, FE, Web, bug

#486 [FE] Fix: LoginForm, NaverLoginButton 컴포넌트 분리
  client/components/atoms/NaverLoginButton/index.tsx
  client/components/molecules/LoginForm/index.tsx
  client/pages/login/index.tsx
Labels: FE, Web

#487 [FE] event timestamp 시간 현재 시간으로 찍히도록 수정
  client/utils/eventLogger.ts
  client/utils/time.ts
Labels: FE, Web
