Repository boostcamp-2020/Project01-B-User-Event-Collector, pull requests merged in 2020-11, with the labels that each got.

#5 [FE] 프론트엔드 프로젝트 환경 설정 추가
  client/.eslintrc.js
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/webpack.config.js
Labels: FE

#9 [iOS] 프로젝트 생성 #8
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MiniVibe/MiniVibe.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MiniVibe/MiniVibe.xcworkspace/contents.xcworkspacedata
  MiniVibe/MiniVibe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MiniVibe/MiniVibe/Assets.xcassets/AccentColor.colorset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/AppIcon.appiconset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/Contents.json
  MiniVibe/MiniVibe/ContentView.swift
  MiniVibe/MiniVibe/Info.plist
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Preview Content/Preview Assets.xcassets/Contents.json
  MiniVibe/Podfile
  MiniVibe/Podfile.lock
Labels: PairProgramming, iOS

#35 [iOS] 차트 뷰 구성 #10, #11, #21
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/album.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/album.imageset/album.jpg
  MiniVibe/MiniVibe/Views/Chart.swift
  MiniVibe/MiniVibe/Views/SectionTitle.swift
  MiniVibe/MiniVibe/Views/TrackRow.swift
Labels: enhancement, iOS🍎

#36 [iOS] TodayTitle 뷰 구현 #12
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/TodayTitle.swift
Labels: PairProgramming, enhancement, iOS🍎

#38 [iOS] 컨텐츠 모아보기 뷰 구현
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/content.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/content.imageset/content.png
  MiniVibe/MiniVibe/Views/Chart.swift
  MiniVibe/MiniVibe/Views/ContentItem.swift
  MiniVibe/MiniVibe/Views/Contents.swift
Labels: PairProgramming, enhancement, iOS🍎

#39 [FE] Button 컴포넌트 작성 #37
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/Button.tsx
  client/src/components/atoms/Button/Button.styles.tsx
  client/src/components/atoms/Button/Button.tsx
Labels: FE, enhancement

#40 [iOS] 플레이리스트 모아보기 뷰 구현 #14, #16
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/playListThumbnail.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/playListThumbnail.imageset/playListThumbnail.png
  MiniVibe/MiniVibe/Views/PlayListItem.swift
  MiniVibe/MiniVibe/Views/PlayListSection.swift
Labels: enhancement, iOS🍎

#42 [iOS] DJ Station 모아보기 뷰 구현 #22 #23
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/station.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/station.imageset/station.png
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Station.swift
  MiniVibe/MiniVibe/Views/StationItem.swift
Labels: enhancement, iOS🍎

#44 [FE] Text 컴포넌트 작성
  client/src/App.tsx
  client/src/components/atoms/Text/Text.styles.tsx
  client/src/components/atoms/Text/Text.tsx
Labels: FE

#46 [iOS] VIBE 추천 플레이리스트 모아보기 뷰 구현
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/recommandedPlayListThumbnail.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/recommandedPlayListThumbnail.imageset/recommandedPlayListThumbnail.png
  MiniVibe/MiniVibe/Views/RecommandedPlayListItem.swift
  MiniVibe/MiniVibe/Views/RecommandedPlayListSection.swift
Labels: enhancement, iOS🍎

#47 [iOS] 매거진 모아보기 뷰 구현 #18, #19
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Assets.xcassets/magazine.imageset/Contents.json
  MiniVibe/MiniVibe/Assets.xcassets/magazine.imageset/magazine.png
  MiniVibe/MiniVibe/Views/MagazineItem.swift
  MiniVibe/MiniVibe/Views/MagazineSection.swift
Labels: enhancement, iOS🍎

#60 [FE] A, Button, Text 컴포넌트 타입스크립트 적용
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/components/atoms/A/A.styles.tsx
  client/src/components/atoms/A/A.tsx
  client/src/components/atoms/Button/Button.styles.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Text/Text.styles.tsx
  client/src/components/atoms/Text/Text.tsx
  client/tsconfig.json
Labels: FE

#61 [iOS] 투데이 뷰 구성 #24
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Chart.swift
  MiniVibe/MiniVibe/Views/ChartSection.swift
  MiniVibe/MiniVibe/Views/ContentItem.swift
  MiniVibe/MiniVibe/Views/ContentSection.swift
  MiniVibe/MiniVibe/Views/Contents.swift
  MiniVibe/MiniVibe/Views/MagazineSection.swift
  MiniVibe/MiniVibe/Views/PlayListSection.swift
  MiniVibe/MiniVibe/Views/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/SectionTitle.swift
  MiniVibe/MiniVibe/Views/StationItem.swift
  MiniVibe/MiniVibe/Views/StationSection.swift
  MiniVibe/MiniVibe/Views/Today.swift
  MiniVibe/MiniVibe/Views/TodayTitle.swift
Labels: PairProgramming, enhancement, iOS🍎

#64 [iOS] 믹스테잎 더보기 화면 구현 #25
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/MixtapeList.swift
  MiniVibe/MiniVibe/Views/SectionTitle.swift
Labels: enhancement, iOS🍎

#65 [iOS] 플레이리스트/매거진 더보기 화면 구현 #26, #27, #30, #34
  MiniVibe/MiniVibe/Views/ListRow.swift
  MiniVibe/MiniVibe/Views/MagazineList.swift
Labels: enhancement, iOS🍎

#69 [iOS] SectionTitle 화면 전환 구현 #68
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/ChartSection.swift
  MiniVibe/MiniVibe/Views/MagazineList.swift
  MiniVibe/MiniVibe/Views/MagazineSection.swift
  MiniVibe/MiniVibe/Views/PlayListSection.swift
  MiniVibe/MiniVibe/Views/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/SectionTitle.swift
  MiniVibe/MiniVibe/Views/StationSection.swift
  MiniVibe/MiniVibe/Views/Today.swift
Labels: PairProgramming, enhancement, iOS🍎

#63 Feat/atom label fe
  client/src/components/atoms/Label/Label.styles.tsx
  client/src/components/atoms/Label/Label.tsx
  client/src/components/atoms/Label/index.ts
Labels: FE, Web, enhancement

#71 [FE] GenreCard 컴포넌트 구현
  client/src/components/molecules/GenreCard/GenreCard.tsx
  client/src/components/molecules/GenreCard/index.tsx
Labels: FE, Web, enhancement

#72 [iOS] SectionTitle 화면 전환 추가 #68
  MiniVibe/MiniVibe/Views/MagazineList.swift
  MiniVibe/MiniVibe/Views/MagazineSection.swift
  MiniVibe/MiniVibe/Views/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today.swift
Labels: enhancement, iOS🍎

#73 [iOS] Feat: 스테이션 더보기 화면 구현 #28
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/ChartSection.swift
  MiniVibe/MiniVibe/Views/ContentSection.swift
  MiniVibe/MiniVibe/Views/MagazineList.swift
  MiniVibe/MiniVibe/Views/MagazineSection.swift
  MiniVibe/MiniVibe/Views/PlayListSection.swift
  MiniVibe/MiniVibe/Views/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/SectionTitle.swift
  MiniVibe/MiniVibe/Views/StationList.swift
  MiniVibe/MiniVibe/Views/StationSection.swift
  MiniVibe/MiniVibe/Views/StationStack.swift
  MiniVibe/MiniVibe/Views/Today.swift
Labels: enhancement, iOS🍎

#75 [iOS] 코드 정리 #74
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/ContentView.swift
  MiniVibe/MiniVibe/Extension/CGFloat+Constant.swift
  MiniVibe/MiniVibe/Views/Common/ChartSection.swift
  MiniVibe/MiniVibe/Views/Common/MixtapeGrid.swift
  MiniVibe/MiniVibe/Views/Common/SectionTitle.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailGrid.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailItem.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailList.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailRow.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailSection.swift
  MiniVibe/MiniVibe/Views/Common/TrackRow.swift
  MiniVibe/MiniVibe/Views/MixtapeList.swift
  MiniVibe/MiniVibe/Views/Today.swift
  MiniVibe/MiniVibe/Views/Today/MagazineItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineSection.swift
  MiniVibe/MiniVibe/Views/Today/PreviewItem.swift
  MiniVibe/MiniVibe/Views/Today/PreviewSection.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListItem.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today/StationItem.swift
  MiniVibe/MiniVibe/Views/Today/StationList.swift
  MiniVibe/MiniVibe/Views/Today/StationSection.swift
  MiniVibe/MiniVibe/Views/Today/StationStack.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
  MiniVibe/Podfile.lock
Labels: PairProgramming, iOS🍎

#76 [iOS] 최근 들은 노래 더보기 화면 구성
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Common/ChartList.swift
  MiniVibe/MiniVibe/Views/Common/ChartSection.swift
  MiniVibe/MiniVibe/Views/Common/PlayAndShuffle.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: PairProgramming, enhancement, iOS🍎

#83 [iOS] TabBar 구현 #78
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/MiniVibeApp.swift
  MiniVibe/MiniVibe/Views/Common/MainTab.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: enhancement, iOS🍎

#84 [iOS] 재생 프리뷰 구현 #80
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/Podfile.lock
Labels: enhancement, iOS🍎

#88 [iOS] 재생 프리뷰 레이아웃 설정 #86
  MiniVibe/MiniVibe/Views/Common/MainTab.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Today/Today.swift
Labels: PairProgramming, enhancement, iOS🍎

#87 [FE] 사이드바 메뉴링크 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/MenuLink/MenuLink.tsx
  client/src/components/atoms/MenuLink/index.ts
Labels: FE, Web, enhancement

#89 frontend typescript 기반 setting
  client/.babelrc
  client/.eslintrc.js
  client/.prettierrc
  client/next-env.d.ts
  client/package-lock.json
  client/package.json
  client/tsconfig.json
Labels: FE, Web, settings

#93 [FE] 드롭다운 컴포넌트 구현
  client/components/molecules/DropdownMenu/DropdownMenu.stories.tsx
  client/components/molecules/DropdownMenu/DropdownMenu.tsx
  client/components/molecules/DropdownMenu/index.ts
Labels: FE, Web, enhancement

#97 Backend settings
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db.ts
  server/src/models/User.ts
  server/src/routes/index.ts
  server/src/routes/user.ts
  server/tsconfig.json
Labels: BE, Web, settings

#98 [iOS] Mock 데이터 제작 #79
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Resource/FavoritePlayList.json
  MiniVibe/MiniVibe/Resource/Magazines.json
  MiniVibe/MiniVibe/Resource/MyMixtape.json
  MiniVibe/MiniVibe/Resource/MyTastePlayList.json
  MiniVibe/MiniVibe/Resource/RecommandedAlbum.json
  MiniVibe/MiniVibe/Resource/RecommandedPlayList.json
  MiniVibe/MiniVibe/Resource/Stations.json
Labels: PairProgramming, iOS🍎

#99 [FE] 유저 프로필 메뉴 컴포넌트 구현
  client/.storybook/main.js
  client/components/atoms/MenuLink/MenuLink.tsx
  client/components/molecules/DropdownMenu/DropdownMenu.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.stories.tsx
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/components/organisms/UserProfileMenu/index.ts
  client/package-lock.json
  client/package.json
Labels: FE, Web

#108 [FE] 헤더사이드바 구현
  client/.storybook/preview.js
  client/components/atoms/MenuLink/MenuLink.tsx
  client/components/molecules/MainMenu/MainMenu.stories.tsx
  client/components/molecules/MainMenu/MainMenu.tsx
  client/components/molecules/MainMenu/index.ts
  client/components/molecules/SearchInput/SearchInput.tsx
  client/components/molecules/SearchInput/index.ts
  client/components/molecules/SubMenu/SubMenu.stories.tsx
  client/components/molecules/SubMenu/SubMenu.tsx
  client/components/molecules/SubMenu/index.ts
  client/components/organisms/HeaderSideBar/HeaderSideBar.stories.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.styles.tsx
  client/components/organisms/HeaderSideBar/HeaderSideBar.tsx
  client/components/organisms/HeaderSideBar/index.ts
  client/components/organisms/UserProfileMenu/UserProfileMenu.tsx
  client/package-lock.json
  client/package.json
Labels: FE, Web, enhancement

#144 [iOS] Network Layer 구현 및 테스트
  MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  MiniVibe/MiniVibe/Models/NetworkService.swift
  MiniVibe/MiniVibe/Views/Common/ChartSection.swift
  MiniVibe/MiniVibe/Views/Common/PlayAndShuffle.swift
  MiniVibe/MiniVibe/Views/Common/PlayerPreview.swift
  MiniVibe/MiniVibe/Views/Common/SectionTitle.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailItem.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailRow.swift
  MiniVibe/MiniVibe/Views/Common/ThumbnailSection.swift
  MiniVibe/MiniVibe/Views/Common/TrackRow.swift
  MiniVibe/MiniVibe/Views/Today/MagazineItem.swift
  MiniVibe/MiniVibe/Views/Today/MagazineSection.swift
  MiniVibe/MiniVibe/Views/Today/PreviewItem.swift
  MiniVibe/MiniVibe/Views/Today/PreviewSection.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListItem.swift
  MiniVibe/MiniVibe/Views/Today/RecommandedPlayListSection.swift
  MiniVibe/MiniVibe/Views/Today/StationItem.swift
  MiniVibe/MiniVibe/Views/Today/StationSection.swift
  MiniVibe/MiniVibe/Views/Today/StationStack.swift
  MiniVibe/MiniVibe/Views/Today/TodayTitle.swift
  MiniVibe/MiniVibeTests/Info.plist
  MiniVibe/MiniVibeTests/MiniVibeTests.swift
  MiniVibe/MiniVibeTests/NetworkError+Equatable.swift
Labels: PairProgramming, enhancement, iOS🍎

#145 [FE] 컨텐츠 카드 부분 코드 리팩토링
  client/components/atoms/Image/Image.stories.tsx
  client/components/atoms/Image/Image.styles.tsx
  client/components/molecules/ArtistThumbnail/LibraryArtistThumbnail/LibraryArtistThumbnail.tsx
  client/components/molecules/ArtistThumbnail/NormalArtistThumbnail/NormalArtistThumbnail.tsx
  client/components/organisms/Cards/AlbumCard/AlbumCard.tsx
  client/components/organisms/Cards/MagazineCard/MagazineCard.tsx
  client/components/organisms/Cards/MainMagazineCard/MainMagazineCard.tsx
  client/components/organisms/Cards/MixtapeCard/MixtapeCard.tsx
  client/components/organisms/Cards/NewsCard/NewsCard.tsx
  client/components/organisms/Cards/PlaylistCard/PlaylistCard.tsx
  client/components/organisms/Cards/StationCard/StationCard.tsx
Labels: FE, Web

#157 [FE] 스크롤 카드리스트 구현
  client/components/atoms/Circle/Circle.tsx
  client/components/molecules/SlideNextButton/SlideNextButton.tsx
  client/components/molecules/SlideNextButton/index.ts
  client/components/molecules/SlidePrevButton/SlidePrevButton.tsx
  client/components/molecules/SlidePrevButton/index.ts
  client/components/organisms/CardScrollList/CardScrollList.stories.tsx
  client/components/organisms/CardScrollList/CardScrollList.styles.tsx
  client/components/organisms/CardScrollList/CardScrollList.tsx
  client/components/organisms/CardScrollList/index.ts
  client/components/organisms/Cards/MagazineCard/index.ts
  client/components/organisms/Cards/NewsCard/index.ts
  client/interfaces/props.ts
  client/tsconfig.json
Labels: FE, Web, enhancement

#153 [FE] 보관함 헤더 컴포넌트 구현
  client/components/organisms/LibraryHeader/LibraryHeader.stories.tsx
  client/components/organisms/LibraryHeader/LibraryHeader.tsx
Labels: FE, Web
